### ISSUE TITLE
pathHeight problem

### ISSUE THREAD

**Issue by janfranek** [vursen/FloatSidebar.js#10]
Hi,
first thanks for this great float sidebar plugin, its very easy to implement and works great.

But, I'm having a little trouble with
`var sideOuterHeight = Math.max(dim$sideInner.height, pathHeight);`

It sets height of my sidebar everytime I scroll and it gets bigger and bigger so I can't scroll to bottom of the page.

So I decided to use only `dim$sideInner.height` and it works fine.

Am I doing something wrong or why should I want to use pathHeight?
Thanks :)

**Comment by vursen** [comment]
Hi, @janfranek, thank you for your issue.

Do you use flexbox with FloatSidebar?

Problem is usually in the wrong css flexbox layout. 

You have to set `align-items: flex-start;` for your parent container, because flex items is stretch by default (https://developer.mozilla.org/en-US/docs/Web/CSS/align-items). After this the problem should be gone.

Example:
```html
<div class="container">
  <div class="content">
    <!-- Content -->
  </div>

  <div class="sidebar">
    <div class="sidebar__inner">
      <!-- Sidebar content -->
    </div>
  </div>
</div>
```

```css
.container {
  display: flex;
   /* Required */
   align-items: flex-start;
}
```

I think I should update README for this particular case.
